In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mymatrix = np.array(mylist)

In [9]:
mymatrix.shape

(3, 3)

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
type(0.)

float

In [15]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(4)


array([0.56272792, 0.69872869, 0.47065937, 0.77797165])

In [22]:
np.random.randn(1)

array([0.19442014])

In [23]:
np.random.seed(42)

In [24]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

39

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.argmin()

9

In [34]:
ranarr.dtype

dtype('int64')

In [2]:
arr = np.arange(0,11)

NameError: name 'np' is not defined

In [1]:
arr


NameError: name 'arr' is not defined

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
arr = arr+1

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [15]:
arr = arr-1

In [16]:
slice_arr = arr[0:6]

In [17]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_arr[:]=99

In [19]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy[:]=1

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [28]:
arr_2d[1]

array([20, 25, 30])

In [29]:
arr_2d[1][1]

25

In [30]:
arr_2d[1,1]

25

In [31]:
arr_2d[2,2]

45

In [32]:
arr_2d[0,0]

5

In [35]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr>4

In [40]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])